<?php

/**
 * @file
 * The renderer behind the data_surface_demo_node_type_tool COMPARISON.md.
 *
 * Not autoloadable, for the same reason as the field tools' renderer
 * beside it: it belongs to the generator script, not to any module's
 * runtime. Both scripts/generate-comparison.php and
 * NodeTypeToolComparisonTest include it, so the document the script
 * writes and the document the test asserts come from one piece of code.
 *
 * @see scripts/generate-comparison.php
 * @see \Drupal\Tests\data_surface\Kernel\NodeTypeToolComparisonTest
 */

declare(strict_types=1);

require_once __DIR__ . '/DataSurfaceComparisonDocument.php';

/**
 * Renders the content type tools comparison document.
 */
final class DataSurfaceNodeTypeComparisonDocument {

  /**
   * The environment variable that turns writing on.
   *
   * The same one the field tools' document answers to, so one generator
   * run rewrites both.
   */
  public const WRITE_VARIABLE = DataSurfaceComparisonDocument::WRITE_VARIABLE;

  /**
   * Where the document lives, relative to the module root.
   */
  public const PATH = 'modules/data_surface_demo_node_type_tool/COMPARISON.md';

  /**
   * Renders the comparison document.
   *
   * @param array $surface
   *   The input schema the surface driven tool advertises.
   * @param array $classic
   *   The input schema the classic tool advertises once the entity type
   *   is known to be node.
   * @param array<int, array{0: string, 1: string, 2: string, 3: string}> $outcomes
   *   One row per case: the case, then what the surface tool, the classic
   *   tool and core's content type form each did with it.
   *
   * @return string
   *   The markdown.
   */
  public static function render(array $surface, array $classic, array $outcomes): string {
    $flags = JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE;
    $table = "| Case | `data_surface:node_type_add` | `tool_belt:entity_bundle_add` | Core's content type form, for a person |\n"
      . "| --- | --- | --- | --- |\n";
    foreach ($outcomes as $row) {
      $table .= '| ' . implode(' | ', array_map([self::class, 'cell'], $row)) . " |\n";
    }
    return self::intro()
      . "\n## What happens\n\n"
      . self::casesNote()
      . "\n" . $table
      . "\n## What an agent is handed: `data_surface:node_type_add`\n\n```json\n"
      . json_encode($surface, $flags)
      . "\n```\n\n## What an agent is handed: `tool_belt:entity_bundle_add`, for `node`\n\n```json\n"
      . json_encode($classic, $flags)
      . "\n```\n";
  }

  /**
   * Makes one value safe to put in a table cell.
   *
   * @param string $value
   *   The cell text.
   *
   * @return string
   *   The text on one line, with its pipes escaped.
   */
  private static function cell(string $value): string {
    return str_replace(['|', "\n"], ['\\|', ' '], $value);
  }

  /**
   * The prose above everything else.
   *
   * @return string
   *   The introduction.
   */
  private static function intro(): string {
    return <<<'MARKDOWN'
# Two ways for an agent to create a content type

Generated by `scripts/generate-comparison.php`; do not edit by hand.
`NodeTypeToolComparisonTest` asserts on every run that this file still
matches what that script produces, and every cell of the table below is
what the test observed, not what anybody expected.

`data_surface_demo_extras` adds two editorial review settings to every
content type, and adds them twice: once to the content type surface
through the build event, and once to core's own content type form
through a form alter, written the way core's own modules write one. Both
store the same third party settings, under the same config schema, with
the same rules:

- `review_deadline`, an integer of seconds from 3600 to 2592000 — one
  hour to thirty days — or nothing. The config schema says all of that
  except the unit: it declares an integer with a Range of 3600 to
  2592000, and the key is not named for what it counts. Core's form asks
  a person for an amount and a unit, hours, days, weeks or business
  days, and turns the pair into seconds in its element validator. The
  surface asks for the same amount and unit, and the same conversion is
  a storage shape the extras module hands the surface, which the target
  applies when it prepares what it writes. Business days follow one
  rule on both sides: counted from the start of a Monday, N business
  days of 24 hours span `N + 2 * floor((N - 1) / 5)` calendar days, so
  ten are twelve days, 1036800 seconds.
- `audience_tags`, a list of lower case tags, each once. Core's form
  takes them as comma-separated text and splits, trims, lower cases and
  de-duplicates what a person typed; the schema says only that it is a
  list of strings.

So the classic side has an accurate, complete schema for the deadline,
and the gap it leaves is not validation. It is meaning: what the stored
integer counts, and how what a person says becomes it, live only in form
code, so an agent reading the schema alone has to infer them. A capable
agent will read 3600 and 2592000 as an hour and thirty days in seconds
and guess the unit right; the table records that it does. The claim is
not that it cannot, but that a correct guess is still unverified
inference, found right or wrong only after the value is stored, while
the surface's caller never infers, because the unit is part of the
contract. Business days are the case no reading of the schema can
answer: the schema-only agent's best inference is in range, accepted,
and wrong.

Neither tool below was written with those settings in mind.
`data_surface:node_type_add` names no key of a content type at all: its
one values input is the content type surface, converted when the tool is
asked for its inputs. `tool_belt:entity_bundle_add` is what an agent has
for creating a content type without surfaces. It derives its
`properties` input from the node type's config schema and the labels on
core's form, and it leaves `third_party_settings` out of what it
advertises on purpose.

Both schemas below were produced by the Tool API's own definition
serializer, which is the document an MCP client or a function calling
model is handed.

MARKDOWN;
  }

  /**
   * The note above the table.
   *
   * @return string
   *   The note.
   */
  private static function casesNote(): string {
    return <<<'MARKDOWN'
Each case is sent to each tool as the value its schema would carry — for
the classic tool, as the stored schema reads, inside the
`third_party_settings` map the tool does not advertise, which is the
only way to reach the settings at all — and typed into core's form as a
person would type it. "Stored" is the content type's
`data_surface_demo_extras` third party settings after the call. Where a
stored value breaks the stored schema, the cell says so: the classic
tool writes without asking it, as core's config save does on any site.
The surface refuses tags it would have to rewrite rather than rewriting
them: the pipeline never turns a value into a different one on a
caller's behalf, so the contract says what a stored tag looks like and a
caller sends that.

MARKDOWN;
  }

}
