<?php

/**
 * @file
 * The renderer behind the data_surface_tool module's COMPARISON.md.
 *
 * Not autoloadable, and deliberately so: it belongs to the generator
 * script beside it, not to the module's runtime. Both the script and
 * FieldToolsComparisonTest include this file, which is the whole point —
 * a document generated by one piece of code and asserted by another is a
 * document with two definitions of correct.
 *
 * @see scripts/generate-comparison.php
 * @see \Drupal\Tests\data_surface\Kernel\FieldToolsComparisonTest
 */

declare(strict_types=1);

/**
 * Renders the comparison document, and normalizes it for comparison.
 *
 * Two methods, and the second is the reason the first is worth having as
 * a class: the drift assertion compares a freshly rendered document with
 * the one in the repository, and both sides go through normalize(), so
 * the parts nobody here controls cannot make the check cry wolf.
 */
final class DataSurfaceComparisonDocument {

  /**
   * The environment variable that turns writing on.
   */
  public const WRITE_VARIABLE = 'DATA_SURFACE_WRITE_COMPARISON';

  /**
   * Renders the comparison document.
   *
   * @param array $surface
   *   The settings schema the surface derived tool advertises.
   * @param array $belt
   *   The settings schema the config schema derived tool advertises.
   *
   * @return string
   *   The markdown.
   */
  public static function render(array $surface, array $belt): string {
    $flags = JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE;
    return self::intro()
      . "\n## From the field type's surface: `data_surface:field_add`\n\n```json\n"
      . json_encode($surface, $flags)
      . "\n```\n\n## From the config schema: `tool_belt:field_add`\n\n```json\n"
      . json_encode($belt, $flags)
      . "\n```\n";
  }

  /**
   * Removes the parts of the document that are not this module's to fix.
   *
   * The country list is the addressing library's, and it gains and loses
   * entries between releases of a dependency nobody here controls. A
   * drift assertion that failed on a library update would be a test that
   * cries wolf, so the list is collapsed to a single marker on both sides
   * of the comparison: that the key is there, carries a vocabulary, and
   * carries the same vocabulary in both documents is the claim; exactly
   * which few hundred codes are in it this month is not.
   *
   * @param string $markdown
   *   The document, generated or read from disk.
   *
   * @return string
   *   The document with volatile lists collapsed.
   */
  public static function normalize(string $markdown): string {
    // Every run of quoted two-letter upper case codes, however it is
    // indented or wrapped, is one country list.
    return preg_replace(
      '/(?:"[A-Z]{2}",?\s*){10,}/',
      "<country codes>\n",
      $markdown,
    ) ?? $markdown;
  }

  /**
   * The prose above the two documents.
   *
   * @return string
   *   The introduction.
   */
  private static function intro(): string {
    return <<<'MARKDOWN'
# Two settings inputs for one field type

Generated by `scripts/generate-comparison.php`; do not edit by hand.
`FieldToolsComparisonTest` asserts on every run that this file still
matches what that script produces, so an edit here is a test failure
rather than a quiet fork.

Both documents below are the `settings` input of a field add tool, for
the `address` field type on `entity_test`, after the entity type, bundle
and field name are known. Both were produced by the Tool API's own
definition serializer normalizing the tool's inputs to JSON Schema,
which is the document an MCP client or a function calling model is
handed. The tools take the same seven inputs; only where the settings
input comes from differs.

What to look at:

- `field_overrides`. The surface names all twelve address properties
  that may be overridden, each with a label and the three values it
  takes. The config schema says it is an array of objects with one
  `override` key and no way to name the property being overridden, so
  the single thing a caller most wants to say cannot be said.
- `available_countries`. The surface resolves the country list live, so
  the list that validates is the list that is offered. The config schema
  says "array of string".
- `fields`. The config schema offers it as an ordinary key. It is
  deprecated, and it silently overrules `field_overrides` whenever it is
  not empty. The surface does not offer it, and every write through the
  surface stores it empty.
- Labels. Both carry the top level ones, because the config schema
  happens to label its four keys. Nothing below the top level is labeled
  on the config schema side, and nothing anywhere carries a vocabulary.

MARKDOWN;
  }

}
