<?php

/**
 * @file
 * The renderer behind docs/catalogue.md.
 *
 * Not autoloadable, like the comparison renderers beside it: it belongs
 * to the generator script, not to the module's runtime. Both
 * scripts/generate-catalogue.php and SurfaceCatalogueTest include it, so
 * the document the script writes and the document the test asserts come
 * from one piece of code.
 *
 * @see scripts/generate-catalogue.php
 * @see \Drupal\Tests\data_surface\Kernel\SurfaceCatalogueTest
 */

declare(strict_types=1);

/**
 * Renders the surface catalogue as markdown.
 */
final class DataSurfaceCatalogueDocument {

  /**
   * The environment variable that turns writing on.
   */
  public const WRITE_VARIABLE = 'DATA_SURFACE_WRITE_CATALOGUE';

  /**
   * Where the document lives, relative to the module root.
   */
  public const PATH = 'docs/catalogue.md';

  /**
   * Renders the catalogue.
   *
   * @param array $catalogue
   *   What SurfaceCatalogue::describe() returns.
   *
   * @return string
   *   The markdown.
   */
  public static function render(array $catalogue): string {
    $document = self::intro();
    $document .= "| Surface | Class | Identity | Situations |\n| --- | --- | --- | --- |\n";
    foreach ($catalogue as $surface) {
      $document .= sprintf(
        "| [`%s`](#%s) | `%s` | %s | %s |\n",
        $surface['id'],
        self::anchor($surface['id']),
        self::short($surface['class']),
        self::codes($surface['identity']),
        self::codes(array_column($surface['situations'], 'id')),
      );
    }
    foreach ($catalogue as $surface) {
      $document .= "\n## " . $surface['id'] . "\n\n";
      $document .= '`' . $surface['class'] . '`, in `' . $surface['module'] . "`.\n\n";
      $document .= '- Identity: ' . self::codes($surface['identity']) . "\n";
      $document .= '- Target: ' . ($surface['target'] === NULL ? 'none; its host or its parent stores it' : '`' . $surface['target'] . '`') . "\n";
      $document .= '- Access: ' . ($surface['access'] === NULL ? 'the situation\'s permission alone' : '`' . $surface['access'] . '`') . "\n";
      if ($surface['plugins'] !== []) {
        $document .= '- Used by: ' . self::codes($surface['plugins']) . "; configured through the plugin's host, never on its own.\n";
      }
      if ($surface['situations'] !== []) {
        $document .= "\n| Situation | Label | Needs | Creates | Permission | On its own | Provided by |\n| --- | --- | --- | --- | --- | --- | --- |\n";
        foreach ($surface['situations'] as $situation) {
          $document .= sprintf(
            "| `%s` | %s | %s | %s | %s | %s | `%s` (`%s`) |\n",
            $situation['id'],
            $situation['label'],
            $situation['parameters'] === [] ? 'nothing' : self::codes($situation['parameters']),
            $situation['creates'] === NULL ? 'once given what it needs' : ($situation['creates'] ? 'yes' : 'no'),
            $situation['permission'] === NULL ? 'none' : '`' . $situation['permission'] . '`',
            self::standalone($surface, $situation),
            self::short($situation['provider']),
            $situation['module'],
          );
        }
      }
      foreach ($surface['alters'] as $alter) {
        $document .= "\n- Altered by `" . $alter['class'] . '` (`' . $alter['module'] . '`), '
          . ($alter['situations'] === [] ? 'in every situation' : 'in ' . self::codes($alter['situations'])) . ".\n";
      }
      foreach ($surface['variants'] as $key => $variants) {
        $document .= "\n- Slot `" . $key . '` is filled by: ';
        $filled = [];
        foreach ($variants as $value => $class) {
          $filled[] = '`' . $value . '` → `' . $class . '`';
        }
        $document .= implode(', ', $filled) . ".\n";
      }
      foreach ($surface['derived'] as $key => $source) {
        $document .= "\n- Slot `" . $key . '` is filled, for every other value, by variants derived from ' . $source . ".\n";
      }
    }
    return $document;
  }

  /**
   * The prose above the catalogue.
   *
   * @return string
   *   The introduction.
   */
  private static function intro(): string {
    return <<<'MARKDOWN'
# Surface catalogue

Generated by `scripts/generate-catalogue.php`; do not edit by hand.
`SurfaceCatalogueTest` asserts on every run that this file still
matches what that script produces.

Every surface the modules in this repository declare, read from the
static layer alone: the `#[Surface]` attribute, the `#[Situation]`
methods and what each needs, the `#[AltersSurface]` classes and the
`#[SurfaceVariant]` ones. A plugin that is its own surface,
`#[UsesSurface]` with no argument, is listed by its plugin class, under
an id from its plugin unless it carries `#[Surface]`, and is used by
itself. Nothing here builds a surface. A situation's
"Creates" is the one fact that is not static — it is on the context
the situation returns — so it is known only for a situation that needs
nothing to start from.

A situation that can be asked "on its own" is also a tool,
`data_surface:<surface>:<situation>`, when `data_surface_tool` is
enabled: its surface names a target, no plugin's configuration is the
surface, and every `%key` placeholder in its permission can be supplied
by one of its parameters. A surface a plugin uses is configured through
the plugin's host. `docs/surfaces.md` says how each part works.


MARKDOWN;
  }

  /**
   * Says whether a situation can be asked on its own, and why not.
   *
   * @param array $surface
   *   The surface, as the catalogue describes it.
   * @param array $situation
   *   The situation, as the catalogue describes it.
   *
   * @return string
   *   "yes", or "no" and the first reason.
   */
  private static function standalone(array $surface, array $situation): string {
    return match (TRUE) {
      $situation['standalone'] => 'yes',
      $surface['target'] === NULL => 'no: no target',
      $surface['plugins'] !== [] => 'no: a plugin\'s',
      default => 'no: nothing supplies ' . self::codes(array_map(static fn (string $key): string => '%' . $key, $situation['unresolvable'])),
    };
  }

  /**
   * Joins values as code spans.
   *
   * @param string[] $values
   *   The values.
   *
   * @return string
   *   The code spans, comma separated, or "none".
   */
  private static function codes(array $values): string {
    return $values === [] ? 'none' : implode(', ', array_map(static fn (string $value): string => '`' . $value . '`', $values));
  }

  /**
   * Shortens a class name, or a Class::method(), to its last segment.
   *
   * @param string $name
   *   The name.
   *
   * @return string
   *   The unqualified name.
   */
  private static function short(string $name): string {
    $position = strrpos($name, '\\');
    return $position === FALSE ? $name : substr($name, $position + 1);
  }

  /**
   * Makes the anchor a heading gets.
   *
   * @param string $id
   *   The heading text.
   *
   * @return string
   *   The anchor, as mkdocs writes it.
   */
  private static function anchor(string $id): string {
    return trim((string) preg_replace('/[^a-z0-9_-]+/', '', strtolower($id)), '-');
  }

}
